version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    links:
      - db
      - kafka
    networks:
      - scribe-net
  db:
    build: ./db
    networks:
      - scribe-net
  zookeeper:
    build: ./zookeeper
    ports:
      - "2181:2181"
    networks:
      - scribe-net
  kafka:
    build: ./kafka
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "Scribe:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - scribe-net
  # faust:
  #   command: >
  #     sh -c "sleep 60"
  #   build: ./faust
  #   ports:
  #     - "6066:6066"
  #   # network_mode: host
  #   links:
  #     - kafka 
    
networks:
  scribe-net: